// Synthetic scenarios exclusively for the dev-only QA middleware, never a live data fallback.
export function detail(id) {
 const f = id===900003 ? [3,5,2] : id===900002 ? [4,2,3,1] : [4,3,3];
 const names=['Alisson Ramses Becker','Trent Alexander-Arnold','Virgil van Dijk','Lucas Hernández','Theo Hernández','Alexis Mac Allister','Ryan Gravenberch','Khvicha Kvaratskhelia','Vinícius José Paixão de Oliveira Júnior','Alexander Isak','Rodrygo Silva de Goes'];
 const home={id:40,name:'Home · 表示テスト',logo:null},away={id:85,name:'Away · 表示テスト',logo:null};
 const make=(team,offset)=>({team,formation:f.join('-'),coach:{name:'Test Coach'},startXI:[1,...f].flatMap((count,row)=>Array.from({length:count},(_,i)=>({grid:`${row+1}:${i+1}`,position:row===0?'G':row===1?'D':row===f.length?'F':'M'}))).map((p,i)=>({...p,id:offset+i+1,name:offset===1000?names[i]:["Test Keeper","Test Rightback","Test Centreback","Test Defender","Test Leftback","Test Midfielder","Test Playmaker","Test Winger","Test Forward","Test Striker","Test Attacker"][i],number:i+1,photo:'/tests/ui/missing.png'})),substitutes:[{id:offset+12,name:'Jean Pierre de la Roche',position:'M',number:12}]});
 const lineups=[make(home,1000),make(away,2000)];
 if(id===900004)lineups[0].startXI[4].grid=null;
 const fixture={id,status:id===900005?'NS':'FT',kickoff:id===900005?'2026-09-08T19:00:00Z':'2026-09-01T19:00:00Z',home,away,competition:'表示テスト大会',competitionId:39,roundLabel:'第1節',goals:id===900005?{home:null,away:null}:{home:2,away:1},score:{halftime:{home:1,away:0}},venue:{name:'QA Stadium'}};
 const events=id===900005?[]:[...lineups.flatMap(l=>l.startXI.slice(3,8).map((p,i)=>({type:'yellow_card',player:p,team:l.team,minute:`${20+i*5}'`,elapsed:20+i*5}))),...lineups.map(l=>({type:'substitution',team:l.team,player:l.startXI[6],assist:l.substitutes[0],minute:"70'",elapsed:70})),{type:'goal',team:home,player:lineups[0].startXI[9],assist:lineups[0].startXI[5],minute:"10'",elapsed:10},{type:'goal',team:home,player:lineups[0].startXI[9],assist:lineups[0].startXI[7],minute:"52'",elapsed:52},{type:'goal',team:away,player:lineups[1].startXI[10],assist:lineups[1].startXI[5],minute:"88'",elapsed:88},{type:'red_card',team:away,player:lineups[1].startXI[3],minute:"90'",elapsed:90}];
 return {fixture,lineups:id===900005?[]:lineups,events,eventIntegrity:{teamAssociation:true,goalScore:'consistent'},statistics:[],availability:{lineups:true,events:true,statistics:true}};
}
export function insights(id) { const d=detail(id===900005?900001:id);return {fixtureId:id,updatedAt:'2026-09-05T15:00:00Z',lineups:d.lineups.map(l=>({...l,predicted:id===900005,evidence:{fixtures:[],roster:'unavailable',injuries:'unavailable',minutes:false},absences:[]})),players:id===900004?null:d.lineups.flatMap(l=>l.startXI.map((p,i)=>({...p,teamId:l.team.id,rating:i===3?null:6.5+i/10}))) }; }
